public enum ErrorCodeEnum : UInt16
{
    NONE = 0,
    INVALID_REQUEST = 100,
    INVALID_EMAIL = 101,
    INVALID_PASSWORD = 102,
    EMAIL_ALREADY_EXISTS = 103,
    EMAIL_DOES_NOT_EXIST = 104,
    PASSWORD_DOES_NOT_MATCH = 105,
    NOT_LOGIN = 106,
    INVALID_TOKEN = 107,
    TOKEN_EXPIRED = 108,
    INTERNAL_SERVER_ERROR = 500,
}