services:
  hive-mysql:
    image: mysql
    container_name: hive-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test1234!
      MYSQL_DATABASE: HiveDatabase
    ports:
      - "10000:3306"
    volumes:
      - ./HiveScema/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hive-network

  hive-redis:
    image: redis
    container_name: hive-redis
    ports:
      - "10001:6379"
    networks:
      - hive-network

  hive-service:
    depends_on:
      - hive-mysql
      - hive-redis
    build:
      context: .
      dockerfile: Dockerfile-Hive
    container_name: hive-server
    ports:
      - 5241:5241
    networks:
      - hive-network

networks:
  hive-network:
