services:
  game-mysql:
    image: mysql
    container_name: game-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test1234!
      MYSQL_DATABASE: GameDatabase
    ports:
      - "10002:3306"
    volumes:
      - ./GameScema/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - game-network

  game-redis:
    image: redis
    container_name: game-redis
    ports:
      - "10003:6379"
    networks:
      - game-network

  api-service:
    depends_on:
      - game-mysql
      - game-redis
    build:
      context: .
      dockerfile: Dockerfile-API
    container_name: api-server
    ports:
      - 5122:5122
    networks:
      - hive-network
      - game-network

  match-service:
    depends_on:
      - game-mysql
      - game-redis
    build:
      context: .
      dockerfile: Dockerfile-Match
    container_name: match-server
    ports:
      - 7000:7000
    networks:
      - game-network

  game-service:
    depends_on:
      - game-mysql
      - game-redis
      - api-service
    build:
      context: .
      dockerfile: Dockerfile-Game
    container_name: game-server
    ports:
      - 7777:7777
    networks:
      - game-network

networks:
  hive-network:
  game-network: